--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0
-- Dumped by pg_dump version 16.0

-- Started on 2026-06-19 17:47:52

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 35687)
-- Name: controllers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.controllers (
    id bigint NOT NULL,
    mac text NOT NULL,
    room_id bigint,
    name text
);


ALTER TABLE public.controllers OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 35692)
-- Name: controllers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.controllers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.controllers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 35693)
-- Name: device_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.device_types (
    id bigint NOT NULL,
    name text NOT NULL,
    description text,
    param_names json
);


ALTER TABLE public.device_types OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 35698)
-- Name: device_types_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.device_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 35699)
-- Name: devices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.devices (
    id bigint NOT NULL,
    name text NOT NULL,
    controller_id bigint NOT NULL,
    type_id bigint NOT NULL,
    port text,
    params json,
    current_values text[]
);


ALTER TABLE public.devices OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 35704)
-- Name: devices_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 35705)
-- Name: events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events (
    id integer NOT NULL,
    value bigint,
    device_id bigint,
    "time" timestamp with time zone
);


ALTER TABLE public.events OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 35708)
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.events_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.events_id_seq OWNER TO postgres;

--
-- TOC entry 4877 (class 0 OID 0)
-- Dependencies: 222
-- Name: events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.events_id_seq OWNED BY public.events.id;


--
-- TOC entry 223 (class 1259 OID 35709)
-- Name: predictions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.predictions (
    id integer NOT NULL,
    event_id bigint,
    "time" timestamp with time zone,
    result text
);


ALTER TABLE public.predictions OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 35714)
-- Name: predictions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.predictions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.predictions_id_seq OWNER TO postgres;

--
-- TOC entry 4878 (class 0 OID 0)
-- Dependencies: 224
-- Name: predictions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.predictions_id_seq OWNED BY public.predictions.id;


--
-- TOC entry 225 (class 1259 OID 35715)
-- Name: roles_names; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles_names (
    id integer NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.roles_names OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 35720)
-- Name: roles_names_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.roles_names_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.roles_names_id_seq OWNER TO postgres;

--
-- TOC entry 4879 (class 0 OID 0)
-- Dependencies: 226
-- Name: roles_names_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.roles_names_id_seq OWNED BY public.roles_names.id;


--
-- TOC entry 227 (class 1259 OID 35721)
-- Name: rooms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rooms (
    id bigint NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.rooms OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 35726)
-- Name: rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 35727)
-- Name: trig_conditions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trig_conditions (
    id integer NOT NULL,
    device_id bigint NOT NULL,
    condition text NOT NULL,
    trigger_id bigint NOT NULL
);


ALTER TABLE public.trig_conditions OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 35732)
-- Name: trig_conditions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.trig_conditions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.trig_conditions_id_seq OWNER TO postgres;

--
-- TOC entry 4880 (class 0 OID 0)
-- Dependencies: 230
-- Name: trig_conditions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.trig_conditions_id_seq OWNED BY public.trig_conditions.id;


--
-- TOC entry 231 (class 1259 OID 35733)
-- Name: trig_responses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trig_responses (
    id bigint NOT NULL,
    device_id bigint NOT NULL,
    resp text,
    trigger_id bigint NOT NULL
);


ALTER TABLE public.trig_responses OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 35738)
-- Name: trig_responses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.trig_responses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.trig_responses_id_seq OWNER TO postgres;

--
-- TOC entry 4881 (class 0 OID 0)
-- Dependencies: 232
-- Name: trig_responses_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.trig_responses_id_seq OWNED BY public.trig_responses.id;


--
-- TOC entry 233 (class 1259 OID 35739)
-- Name: triggers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.triggers (
    id integer NOT NULL,
    controller_id bigint NOT NULL,
    controller_resp_id bigint,
    name text
);


ALTER TABLE public.triggers OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 35744)
-- Name: triggers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.triggers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.triggers_id_seq OWNER TO postgres;

--
-- TOC entry 4882 (class 0 OID 0)
-- Dependencies: 234
-- Name: triggers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.triggers_id_seq OWNED BY public.triggers.id;


--
-- TOC entry 235 (class 1259 OID 35745)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    name text,
    pass text,
    role_id bigint NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 35750)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO postgres;

--
-- TOC entry 4883 (class 0 OID 0)
-- Dependencies: 236
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- TOC entry 4684 (class 2604 OID 35751)
-- Name: events id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events ALTER COLUMN id SET DEFAULT nextval('public.events_id_seq'::regclass);


--
-- TOC entry 4685 (class 2604 OID 35752)
-- Name: predictions id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.predictions ALTER COLUMN id SET DEFAULT nextval('public.predictions_id_seq'::regclass);


--
-- TOC entry 4686 (class 2604 OID 35753)
-- Name: roles_names id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles_names ALTER COLUMN id SET DEFAULT nextval('public.roles_names_id_seq'::regclass);


--
-- TOC entry 4687 (class 2604 OID 35754)
-- Name: trig_conditions id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trig_conditions ALTER COLUMN id SET DEFAULT nextval('public.trig_conditions_id_seq'::regclass);


--
-- TOC entry 4688 (class 2604 OID 35755)
-- Name: trig_responses id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trig_responses ALTER COLUMN id SET DEFAULT nextval('public.trig_responses_id_seq'::regclass);


--
-- TOC entry 4689 (class 2604 OID 35756)
-- Name: triggers id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.triggers ALTER COLUMN id SET DEFAULT nextval('public.triggers_id_seq'::regclass);


--
-- TOC entry 4690 (class 2604 OID 35757)
-- Name: users id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- TOC entry 4692 (class 2606 OID 35759)
-- Name: controllers controllers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.controllers
    ADD CONSTRAINT controllers_pkey PRIMARY KEY (id);


--
-- TOC entry 4694 (class 2606 OID 35761)
-- Name: device_types device_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.device_types
    ADD CONSTRAINT device_types_pkey PRIMARY KEY (id);


--
-- TOC entry 4696 (class 2606 OID 35763)
-- Name: devices devices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_pkey PRIMARY KEY (id);


--
-- TOC entry 4698 (class 2606 OID 35765)
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- TOC entry 4700 (class 2606 OID 35767)
-- Name: predictions predictions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.predictions
    ADD CONSTRAINT predictions_pkey PRIMARY KEY (id);


--
-- TOC entry 4702 (class 2606 OID 35769)
-- Name: roles_names roles_names_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles_names
    ADD CONSTRAINT roles_names_pkey PRIMARY KEY (id);


--
-- TOC entry 4704 (class 2606 OID 35771)
-- Name: rooms rooms_name_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_name_uniq UNIQUE (name);


--
-- TOC entry 4706 (class 2606 OID 35773)
-- Name: rooms rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);


--
-- TOC entry 4708 (class 2606 OID 35775)
-- Name: trig_conditions trig_conditions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trig_conditions
    ADD CONSTRAINT trig_conditions_pkey PRIMARY KEY (id);


--
-- TOC entry 4710 (class 2606 OID 35777)
-- Name: trig_responses trig_responses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trig_responses
    ADD CONSTRAINT trig_responses_pkey PRIMARY KEY (id);


--
-- TOC entry 4712 (class 2606 OID 35779)
-- Name: triggers triggers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.triggers
    ADD CONSTRAINT triggers_pkey PRIMARY KEY (id);


--
-- TOC entry 4714 (class 2606 OID 35781)
-- Name: users users_name_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_name_uniq UNIQUE (name);


--
-- TOC entry 4716 (class 2606 OID 35783)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4718 (class 2606 OID 35784)
-- Name: devices controller_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT controller_id FOREIGN KEY (controller_id) REFERENCES public.controllers(id) NOT VALID;


--
-- TOC entry 4720 (class 2606 OID 35789)
-- Name: events device_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT device_id FOREIGN KEY (device_id) REFERENCES public.devices(id) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID;


--
-- TOC entry 4717 (class 2606 OID 35794)
-- Name: controllers id_room; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.controllers
    ADD CONSTRAINT id_room FOREIGN KEY (room_id) REFERENCES public.rooms(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 4721 (class 2606 OID 35799)
-- Name: predictions predictions_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.predictions
    ADD CONSTRAINT predictions_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 4728 (class 2606 OID 35804)
-- Name: users role_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT role_id FOREIGN KEY (role_id) REFERENCES public.roles_names(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 4722 (class 2606 OID 35809)
-- Name: trig_conditions trig_conditions_device_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trig_conditions
    ADD CONSTRAINT trig_conditions_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id);


--
-- TOC entry 4723 (class 2606 OID 35814)
-- Name: trig_conditions trig_conditions_trigger_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trig_conditions
    ADD CONSTRAINT trig_conditions_trigger_id_fkey FOREIGN KEY (trigger_id) REFERENCES public.triggers(id) NOT VALID;


--
-- TOC entry 4724 (class 2606 OID 35819)
-- Name: trig_responses trig_responses_device_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trig_responses
    ADD CONSTRAINT trig_responses_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id);


--
-- TOC entry 4725 (class 2606 OID 35824)
-- Name: trig_responses trig_responses_trigger_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trig_responses
    ADD CONSTRAINT trig_responses_trigger_id_fkey FOREIGN KEY (trigger_id) REFERENCES public.triggers(id) NOT VALID;


--
-- TOC entry 4726 (class 2606 OID 35829)
-- Name: triggers triggers_controller_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.triggers
    ADD CONSTRAINT triggers_controller_id_fkey FOREIGN KEY (controller_id) REFERENCES public.controllers(id);


--
-- TOC entry 4727 (class 2606 OID 35834)
-- Name: triggers triggers_controller_resp_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.triggers
    ADD CONSTRAINT triggers_controller_resp_id_fkey FOREIGN KEY (controller_resp_id) REFERENCES public.controllers(id) NOT VALID;


--
-- TOC entry 4719 (class 2606 OID 35839)
-- Name: devices type; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT type FOREIGN KEY (type_id) REFERENCES public.device_types(id) NOT VALID;


-- Completed on 2026-06-19 17:47:52

--
-- PostgreSQL database dump complete
--

